name: local_roots_2
description: "Local Roots v.2"
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  go_router: ^14.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.3.2
  flutter_form_builder: ^9.5.0
  sign_button: ^2.0.6
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  form_builder_validators: ^11.0.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  uuid: ^4.5.1
  google_geocoding_api: ^1.5.2
  google_maps_flutter: ^2.9.0
  cached_network_image: ^3.4.1
  image: ^4.3.0
  jiffy: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  riverpod_lint: ^2.6.1


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
