// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsGssWGHuEqRsFskRdr_QAW1__M2dsP1k',
    appId: '1:126521181954:web:44b09b6f77832e2dae641b',
    messagingSenderId: '126521181954',
    projectId: 'local-roots-2',
    authDomain: 'local-roots-2.firebaseapp.com',
    storageBucket: 'local-roots-2.appspot.com',
    measurementId: 'G-SS770XJGYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_8r5Nk47rz2dR6pdTSW9MvDFlagcJWCw',
    appId: '1:126521181954:android:b6800e7b51707a38ae641b',
    messagingSenderId: '126521181954',
    projectId: 'local-roots-2',
    storageBucket: 'local-roots-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53tU8oD5n-oxKGAfThvOOP_1lQmEJMXM',
    appId: '1:126521181954:ios:22aabdc684cc8bebae641b',
    messagingSenderId: '126521181954',
    projectId: 'local-roots-2',
    storageBucket: 'local-roots-2.appspot.com',
    iosClientId: '126521181954-7sj13c717tea7o43rb31fb3rn8bke5nb.apps.googleusercontent.com',
    iosBundleId: 'com.dot4soft.localRoots2',
  );

}